global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "kubernetes-pods"
    kubernetes_sd_configs:
      - role: pod

  - job_name: "backend-service"
    static_configs:
      - targets: ["backend-service:5000"]

  - job_name: "frontend-service"
    static_configs:
      - targets: ["frontend-service:80"]